DATA:
    ROOT: 'E:\\yolo_track\\X-CLIP\\dataset\\videos'
    TRAIN_FILE: 'E:\\yolo_track\\X-CLIP\\dataset\\train.txt'
    VAL_FILE: 'E:\\yolo_track\\X-CLIP\\dataset\\val.txt'
    DATASET: hmdb51
    NUM_FRAMES: 32
    NUM_CLASSES: 51
    LABEL_LIST: 'labels/hmdb_51_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4
    ACCUMULATION_STEPS: 2
    EPOCHS: 50
    LR: 2.e-6